import pathlib
from typing import Tuple, Union
import numpy as np
import pandas as pd

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        self.data_fname = pathlib.Path(data_fname)
        if not self.data_fname.exists():
            raise ValueError(f"The file does not exist.")
        self.data = None

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        with open(self.data_fname, "r") as file_object:
            raw_data = file_object.read()       
        self.data = pd.read_json(raw_data)

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """Calculates and plots the age distribution of the participants.
        Returns
        -------
        hist : np.ndarray
        Number of people in a given bin
        bins : np.ndarray
        Bin edges
            """        
        bins = np.arange(0, 101, 10)
        ages = pd.to_numeric(self.data['age'].dropna())        
        hist, bin_edges = np.histogram(ages, bins=bins)
        return hist, bin_edges
    
    def remove_rows_without_mail(self) -> pd.DataFrame:
        """Checks self.data for rows with invalid emails, and removes them.

    Returns
    -------
    df : pd.DataFrame
    A corrected DataFrame, i.e. the same table but with the erroneous rows removed and
    the (ordinal) index after a reset.
        """
        emails = self.data['email']     
        return emails[
    (emails.str.count("@") == 1) &
    (~emails.str.startswith("@")) &
    (~emails.str.endswith("@")) &
    (emails.str.contains(".", regex = False)) &
    (~emails.str.startswith(".")) &
    (~emails.str.endswith(".")) &
    (~emails.str.contains("@\\."))
 ].reset_index(drop=True).to_frame()

    def fill_na_with_mean(self) -> Tuple[pd.DataFrame, np.ndarray]:
        """Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student.

        Returns
        -------
        df : pd.DataFrame
        The corrected DataFrame after insertion of the mean grade
        arr : np.ndarray
            Row indices of the students that their new grades were generated
            """
        
        df = self.data.copy()
        question_cols = [col for col in df.columns if col.startswith('q')]
        
        corrected_indices = []

        for i, row in df.iterrows():
            if row[question_cols].isna().any():
                mean_value = row[question_cols].mean()
                df.loc[i, question_cols] = row[question_cols].fillna(mean_value)
                corrected_indices.append(i)
        
        corrected_indices = np.array(corrected_indices)
        return df, corrected_indices

    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:
        """Calculates the average score of a subject and adds a new "score" column
        with it.

        If the subject has more than "maximal_nans_per_sub" NaN in his grades, the
        score should be NA. Otherwise, the score is simply the mean of the other grades.
        The datatype of score is UInt8, and the floating point raw numbers should be
        rounded down.

        Parameters
        ----------
        maximal_nans_per_sub : int, optional
            Number of allowed NaNs per subject before giving a NA score.

        Returns
        -------
        pd.DataFrame
            A new DF with a new column - "score".
        """
        df = self.data.copy()
        question_cols = [col for col in df.columns if col.startswith('q')]
        df['nan_count'] = df[question_cols].isna().sum(axis=1)
        df['score'] = np.floor(df[question_cols].mean(axis=1)).astype('UInt8')
        df.loc[df['nan_count'] > maximal_nans_per_sub, 'score'] = pd.NA
        df.drop(columns=['nan_count'], inplace=True)

        return df
